# Generated by Django 3.2 on 2021-05-03 05:33

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210503_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordrawing',
            name='image',
            field=models.ImageField(storage=pathlib.PurePosixPath('/home/spartan327/python-projects/site-portfolio/gallery/media'), upload_to='', verbose_name='Изображение'),
        ),
    ]
