# Generated by Django 3.2 on 2021-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_vectordrawing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordrawing',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
