# Generated by Django 3.2 on 2021-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210503_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vectordrawing',
            name='tags',
            field=models.ManyToManyField(to='gallery.Tag', verbose_name='Теги'),
        ),
    ]
