# Generated by Django 3.2 on 2021-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210503_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordrawing',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='entries', to='gallery.Tag', verbose_name='Теги'),
        ),
    ]
