# Generated by Django 3.2 on 2021-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_vectordrawing_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordrawing',
            name='tags',
            field=models.ManyToManyField(related_name='entries', to='gallery.Tag', verbose_name='Теги'),
        ),
    ]
