# Generated by Django 3.2 on 2021-06-03 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0010_alter_vectordrawing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordrawing',
            name='vector_file',
            field=models.FileField(blank=True, null=True, upload_to='vector_files/', verbose_name='Векторный рисунок'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vector_drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='gallery.vectordrawing')),
            ],
        ),
    ]
